# Generated by Django 3.2.6 on 2021-08-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('sowing_months', models.CharField(blank=True, max_length=100, null=True)),
                ('days_until_harvest', models.IntegerField(blank=True, null=True)),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('productivity', models.IntegerField(blank=True, null=True)),
                ('transplant', models.BooleanField(blank=True, null=True)),
                ('germination_days', models.IntegerField(blank=True, null=True)),
                ('water_needed', models.IntegerField(blank=True, choices=[(0, 'Low need'), (1, 'Medium need'), (2, 'High need')], null=True)),
                ('sun_requirement', models.IntegerField(blank=True, choices=[(0, 'Shadow'), (1, 'Half shadow'), (2, 'Sun')], null=True)),
                ('auxiliar_plants', models.TextField(blank=True, null=True)),
                ('auxiliar_seeds', models.ManyToManyField(blank=True, to='seed.Seed', verbose_name='Auxiliar seeds')),
            ],
        ),
    ]
