# Generated by Django 3.2.6 on 2021-09-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0004_auto_20210826_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
