# Generated by Django 3.2.6 on 2021-09-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0005_seed_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='germination_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='seed',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
