# Generated by Django 3.2.6 on 2021-09-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0006_auto_20210926_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'seed_origin',
            },
        ),
        migrations.AlterModelTable(
            name='seed',
            table='seed',
        ),
    ]
