# Generated by Django 3.2.6 on 2021-09-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0007_auto_20210926_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='origin_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.seedorigin', verbose_name='Origin'),
        ),
    ]
