# Generated by Django 3.2.6 on 2021-09-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0008_seed_origin_link'),
    ]

    def link_seeds(apps, schema_editor):
        seeds = apps.get_model('seed', 'Seed')
        seedOrigin = apps.get_model('seed', 'SeedOrigin')
        for seed in seeds.objects.all():
            if seed.origin:
                seed_origin, created = seedOrigin.objects.get_or_create(name=seed.origin)
                seed.origin_link = seed_origin
                seed.save()
    
    operations = [
        migrations.RunPython(link_seeds)
    ]
