# Generated by Django 3.2.6 on 2021-09-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0009_transfer_seeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='origin',
        ),
    ]
