# Generated by Django 3.2.6 on 2021-09-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0010_remove_seed_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seed',
            old_name='origin_link',
            new_name='origin',
        ),
    ]
