# Generated by Django 3.2.6 on 2021-08-26 17:53

from django.db import migrations, models


def fill_table(apps, schema_editor):
    all_months = ["January", "February", "March", "April", "May", 
                  "June", "July", "August", "September", "October",
                  "November", "December"]
    month = apps.get_model("core", "Month")
    for name in all_months:
        month.objects.create(name=name)

class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RunPython(fill_table)
    ]
